### PR TITLE
[WiP] Infinity probe amount

### PR DESCRIPTION
**Pull request by michielbdejong**
Attempt at fixing https://github.com/interledgerjs/ilp-routing/issues/43

Needs some more work, apparently :)

### CODE REVIEW

**Comment by michielbdejong** [comment]
This change seems to be incompatible with ilp-routing; seeing this error in unit tests:

> BigNumber Error: new BigNumber() number type has more than 15 significant digits: 9.422205438066466e+99

**Comment by sentientwaffle** [comment]
Liquidity curves points are going to be `UInt64`s, so setting the `PROBE_SOURCE_AMOUNT` to `new BigNumber(2).pow(64).minus(1)` should be safe.

**Comment by michielbdejong** [comment]
testing this on https://github.com/interledgerjs/ilp-connector/commits/mj-test-dj-ilqp now

**Comment by michielbdejong** [comment]
superseded by #350

**Pull request closed without merging**
