### PR TITLE
fix: fixerio: throw on getCurve if rates are undefined

### PR DESCRIPTION
**Pull request by vhpoet**
Just a suggestion, because the `BigNumber Error: new BigNumber() not a number: undefined` exception is super annoying.

### CODE REVIEW

**Comment by sentientwaffle** [comment]
I don't understand how this would be triggered. `backend.connect()` is called before `getCurve` ever is (https://github.com/interledgerjs/ilp-connector/blob/cb839567a81c0ac47344eeaa160d9f592eccd562/src/app.js#L27-L38). Are you sure it's not trying to get the curve for currencies that fixerio doesn't know about?

**Comment by vhpoet** [comment]
@sentientwaffle maybe not before it's connected but the `destinationRate` and `sourceRate` are undefined.

**Comment by sentientwaffle** [comment]
Ok, in that case the error message `getCurve is called before the backend is connected` is inaccurate.

**Comment by vhpoet** [comment]
@sentientwaffle how about now

**Comment by sentientwaffle** [comment]
How about separate error messages for when `destinationRate` vs `sourceRate` are missing; something like `throw new ServerError('No rate available for currency ' + params.destination_currency)`.

**Comment by vhpoet** [comment]
@sentientwaffle yep, much better. Updated.

**Pull request merged**
